services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=CSC8113_GroupProject"
      - "POSTGRES_PASSWORD=090807"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432"
  redis:
    image: "redis:latest"
    ports:
      - "6379"
