apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: bookstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: cartservice
          image: gcr.io/csc8113-group8/cart-service
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: bookstore-config
            - secretRef:
                name: bookstore-secrets
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookstore-config
                  key: DB_HOST
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookstore-config
                  key: REDIS_HOST
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: JWT_SECRET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bookstore-secrets
                  key: DB_PASSWORD
          ports:
            - containerPort: 8001
          livenessProbe:
            httpGet:
              path: /cart/health
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /cart/ready
              port: 8001
              scheme: HTTP
            initialDelaySeconds: 25
            periodSeconds: 30
            failureThreshold: 5

---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: bookstore
spec:
  selector:
    app: cartservice
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP
