# blue deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-blue
  namespace: bookstore
  labels:
    app: catalog-service
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
      version: blue
  template:
    metadata:
      labels:
        app: catalog-service
        version: blue
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: catalog-service
          image: gcr.io/csc8113-group8/catalog-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:090807@postgres:5432/CSC8113_GroupProject"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

---
# green deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-green
  namespace: bookstore
  labels:
    app: catalog-service
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
      version: green
  template:
    metadata:
      labels:
        app: catalog-service
        version: green
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: catalog-service
          image: gcr.io/csc8113-group8/catalog-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:090807@postgres:5432/CSC8113_GroupProject"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: bookstore
  labels:
    app: catalog-service
spec:
  selector:
    app: catalog-service
    version: blue # controls which deployment receives traffic
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
