apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore-frontend-ingress
  namespace: bookstore
spec:
  ingressClassName: "nginx"
  rules:
    - host: csc8113-group8.csproject.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 3000
