apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: catalogservice-hpa
  namespace: bookstore
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: catalog-service
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Scale up when CPU usage exceeds 60%
