name: Cart Service CI/CD

on:
  push:
    branches: [main]
    paths:
      - "cart-service/**"
  pull_request:
    branches: [main]
    paths:
      - "cart-service/**"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  CART_SERVICE_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/cart-service

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cart-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set execute permission for Maven wrapper
        run: chmod +x ./cart-service/mvnw

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run tests
        run: ./mvnw test

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.CART_SERVICE_IMAGE }} .
          docker push ${{ env.CART_SERVICE_IMAGE }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}

      - name: Update deployment image
        run: |
          sed -i "s|image: gcr.io/.*\/cart-service:.*|image: ${{ env.CART_SERVICE_IMAGE }}|g" k8s-manifests/cart-service.yml
          kubectl rollout restart deployment/cartservice -n bookstore

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/cartservice -n bookstore
