name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - "frontend/**"
  pull_request:
    branches: [main]
    paths:
      - "frontend/**"
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER_NAME }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  FRONTEND_IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: install dependencies
        run: npm ci

      - name: build application
        run: npm run build

      - name: authenticate to google cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: setup google cloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: configure docker for GCR
        run: gcloud auth configure-docker

      - name: build and push docker image
        run: |
          docker build -t ${{ env.FRONTEND_IMAGE }} .
          docker push ${{ env.FRONTEND_IMAGE }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: authenticate to google cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: setup google cloud cli
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: get GKE credentials
        uses: google-github-actions/get-gke-credentials@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID}}
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}

      - name: update deployment image
        run: |
          sed -i "s|image: gcr.io/.*\/frontend:.*|image: ${{ env.FRONTEND_IMAGE }}|g" k8s-manifests/frontend.yml
          kubectl rollout restart deployment/frontend -n bookstore

      - name: verify deployment
        run: |
          kubectl rollout status deployment/frontend -n bookstore
